#language: csharp
#solution: ConsoleApp1/ConsoleApp1.sln
#
#script:
#  - msbuild /p:Configuration=Debug ConsoleApp1/ConsoleApp1.sln
#
#notifications:
#  - email: false
#
language: csharp
solution: ConsoleApp1/ConsoleApp1.sln
